"""initial schema

Revision ID: 36484c036213
Revises: 
Create Date: 2026-07-17 22:58:29.242840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36484c036213'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('actor_uuid', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_uuid', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_uuid'), ['actor_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('class_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('class_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_types_id'), ['id'], unique=False)

    op.create_table('gym_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('gym_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gym_locations_id'), ['id'], unique=False)

    op.create_table('kiosk_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pin_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kiosk_auth', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kiosk_auth_id'), ['id'], unique=False)

    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_id'), ['id'], unique=False)

    op.create_table('rank_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('degree', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('target_points', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rank_tiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rank_tiers_id'), ['id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)

    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_name')
    )
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terms_id'), ['id'], unique=False)

    op.create_table('website_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('website_themes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_website_themes_id'), ['id'], unique=False)

    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_uuid', sa.String(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('gym_id', sa.Integer(), nullable=True),
    sa.Column('class_type_id', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_type_id'], ['class_types.id'], ),
    sa.ForeignKeyConstraint(['gym_id'], ['gym_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_class_uuid'), ['class_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_classes_id'), ['id'], unique=False)

    op.create_table('term_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('term_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_term_targets_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('pin_hash', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('rank_tier_id', sa.Integer(), nullable=True),
    sa.Column('last_graded_date', sa.Date(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('nicknames', sa.String(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('image_offset_x', sa.Float(), nullable=True),
    sa.Column('image_offset_y', sa.Float(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rank_tier_id'], ['rank_tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_user_uuid'), ['user_uuid'], unique=True)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_uuid', sa.String(), nullable=True),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('author_uuid', sa.String(), nullable=True),
    sa.Column('target_user_uuid', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_uuid'], ['users.user_uuid'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['target_user_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_comment_uuid'), ['comment_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_comments_id'), ['id'], unique=False)

    op.create_table('curricula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id')
    )
    with op.batch_alter_table('curricula', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curricula_id'), ['id'], unique=False)

    op.create_table('invite_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_tokens_token_hash'), ['token_hash'], unique=True)

    op.create_table('points_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('reference_rank_tier_id', sa.Integer(), nullable=True),
    sa.Column('previous_rank_tier_id', sa.Integer(), nullable=True),
    sa.Column('new_rank_tier_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('adjusted_by_uuid', sa.String(), nullable=False),
    sa.Column('adjustment_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adjusted_by_uuid'], ['users.user_uuid'], ),
    sa.ForeignKeyConstraint(['new_rank_tier_id'], ['rank_tiers.id'], ),
    sa.ForeignKeyConstraint(['previous_rank_tier_id'], ['rank_tiers.id'], ),
    sa.ForeignKeyConstraint(['reference_rank_tier_id'], ['rank_tiers.id'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('points_adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_points_adjustments_id'), ['id'], unique=False)

    op.create_table('reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reset_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reset_tokens_token_hash'), ['token_hash'], unique=True)

    op.create_table('session_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_jti', sa.String(), nullable=True),
    sa.Column('user_uuid', sa.String(), nullable=True),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_tokens_token_jti'), ['token_jti'], unique=True)

    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_id'), ['id'], unique=False)

    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lesson_plan_url', sa.String(), nullable=True),
    sa.Column('video_folder_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_id'), ['id'], unique=False)

    op.create_table('class_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('class_date', sa.Date(), nullable=False),
    sa.Column('teacher_uuid', sa.String(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['teacher_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_instances_id'), ['id'], unique=False)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('class_instance_id', sa.Integer(), nullable=True),
    sa.Column('teacher_uuid', sa.String(), nullable=True),
    sa.Column('user_role_id', sa.Integer(), nullable=True),
    sa.Column('attendance_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('confirmed_by', sa.String(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['class_instance_id'], ['class_instances.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.user_uuid'], ),
    sa.ForeignKeyConstraint(['teacher_uuid'], ['users.user_uuid'], ),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_id'), ['id'], unique=False)

    op.create_table('class_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=True),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.Column('class_instance_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], ),
    sa.ForeignKeyConstraint(['class_instance_id'], ['class_instances.id'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_feedback_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_feedback_id'))

    op.drop_table('class_feedback')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_id'))

    op.drop_table('attendance')
    with op.batch_alter_table('class_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_instances_id'))

    op.drop_table('class_instances')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_id'))

    op.drop_table('user_roles')
    with op.batch_alter_table('session_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_tokens_token_jti'))
        batch_op.drop_index(batch_op.f('ix_session_tokens_id'))

    op.drop_table('session_tokens')
    with op.batch_alter_table('reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reset_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_reset_tokens_id'))

    op.drop_table('reset_tokens')
    with op.batch_alter_table('points_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_points_adjustments_id'))

    op.drop_table('points_adjustments')
    with op.batch_alter_table('invite_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_invite_tokens_id'))

    op.drop_table('invite_tokens')
    with op.batch_alter_table('curricula', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curricula_id'))

    op.drop_table('curricula')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_id'))
        batch_op.drop_index(batch_op.f('ix_comments_comment_uuid'))

    op.drop_table('comments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_uuid'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('term_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_term_targets_id'))

    op.drop_table('term_targets')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_id'))
        batch_op.drop_index(batch_op.f('ix_classes_class_uuid'))

    op.drop_table('classes')
    with op.batch_alter_table('website_themes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_website_themes_id'))

    op.drop_table('website_themes')
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terms_id'))

    op.drop_table('terms')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    with op.batch_alter_table('rank_tiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rank_tiers_id'))

    op.drop_table('rank_tiers')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_id'))

    op.drop_table('news')
    with op.batch_alter_table('kiosk_auth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kiosk_auth_id'))

    op.drop_table('kiosk_auth')
    with op.batch_alter_table('gym_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gym_locations_id'))

    op.drop_table('gym_locations')
    with op.batch_alter_table('class_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_types_id'))

    op.drop_table('class_types')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_uuid'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
